<a href="https://colab.research.google.com/github/HebaSedik/deep-learning/blob/master/word_embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from numpy import array
from keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [6]:
corpus = [
     # Positive Reviews
     'This is an excellent movie','The move was fantastic I like it',
      'You should watch it is brilliant','Exceptionally good',
     'Wonderfully directed and executed I like it','Its a fantastic series',
     'Never watched such a brillent movie','It is a Wonderful movie',
      # Negtive Reviews
     "horrible acting", 'waste of money','pathetic picture',
      'It was very boring', 'I did not like the movie','The movie was horrible',
     'I will not recommend', 'The acting is pathetic'
]

In [7]:
sentiments = array([1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0])

In [8]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
all_words = []
for sent in corpus:
   tokenize_word = word_tokenize(sent)
   for word in tokenize_word:
    all_words.append(word)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [9]:
unique_words = set(all_words)
print(len(unique_words))

45


In [10]:
embedded_sentences = [one_hot(sent, 50) for sent in corpus]
print(embedded_sentences )

[[36, 23, 44, 45, 28], [29, 46, 9, 17, 3, 29, 39], [35, 23, 34, 39, 23, 44], [11, 6], [29, 2, 46, 16, 3, 29, 39], [10, 6, 17, 22], [12, 1, 16, 6, 21, 28], [39, 23, 6, 41, 28], [8, 40], [8, 28, 3], [9, 6], [39, 9, 5, 33], [3, 48, 11, 29, 29, 28], [29, 28, 9, 8], [3, 14, 11, 8], [29, 40, 23, 9]]


In [11]:
word_count = lambda sentence: len(word_tokenize(sentence))
longest_sentence = max(corpus, key=word_count)
length_long_sentence = len(word_tokenize(longest_sentence))

In [13]:
padded_sentences = pad_sequences(embedded_sentences, length_long_sentence, padding='post')
print(padded_sentences)

[[36 23 44 45 28  0  0]
 [29 46  9 17  3 29 39]
 [35 23 34 39 23 44  0]
 [11  6  0  0  0  0  0]
 [29  2 46 16  3 29 39]
 [10  6 17 22  0  0  0]
 [12  1 16  6 21 28  0]
 [39 23  6 41 28  0  0]
 [ 8 40  0  0  0  0  0]
 [ 8 28  3  0  0  0  0]
 [ 9  6  0  0  0  0  0]
 [39  9  5 33  0  0  0]
 [ 3 48 11 29 29 28  0]
 [29 28  9  8  0  0  0]
 [ 3 14 11  8  0  0  0]
 [29 40 23  9  0  0  0]]


In [14]:
word_count = lambda sentence: len(word_tokenize(sentence))
longest_sentence = max(corpus, key=word_count)
length_long_sentence = len(word_tokenize(longest_sentence))

## *build model*

In [15]:
model = Sequential()
model.add(Embedding(50, 20, input_length=length_long_sentence))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 7, 20)             1000      
                                                                 
 flatten (Flatten)           (None, 140)               0         
                                                                 
 dense (Dense)               (None, 1)                 141       
                                                                 
Total params: 1,141
Trainable params: 1,141
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 7, 20)             1000      
                                                                 
 flatten (Flatten)           (None, 140)               0         
                                                                 
 dense (Dense)               (None, 1)                 141       
                                                                 
Total params: 1,141
Trainable params: 1,141
Non-trainable params: 0
_________________________________________________________________
None


In [18]:
model.fit(padded_sentences, sentiments, epochs=100, verbose=1)

Epoch 1/100
1/1 [==============================] - 6s 6s/step - loss: 0.7019 - acc: 0.4375
Epoch 2/100
1/1 [==============================] - 0s 14ms/step - loss: 0.6982 - acc: 0.4375
Epoch 3/100
1/1 [==============================] - 0s 11ms/step - loss: 0.6946 - acc: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 11ms/step - loss: 0.6909 - acc: 0.5625
Epoch 5/100
1/1 [==============================] - 0s 10ms/step - loss: 0.6873 - acc: 0.5625
Epoch 6/100
1/1 [==============================] - 0s 12ms/step - loss: 0.6837 - acc: 0.6875
Epoch 7/100
1/1 [==============================] - 0s 13ms/step - loss: 0.6801 - acc: 0.6875
Epoch 8/100
1/1 [==============================] - 0s 10ms/step - loss: 0.6765 - acc: 0.6875
Epoch 9/100
1/1 [==============================] - 0s 11ms/step - loss: 0.6729 - acc: 0.7500
Epoch 10/100
1/1 [==============================] - 0s 9ms/step - loss: 0.6693 - acc: 0.8750
Epoch 11/100
1/1 [==============================] - 0s 10ms/step - loss:

In [19]:
loss, accuracy = model.evaluate(padded_sentences, sentiments, verbose=0)
print('Accuracy: %f' , (accuracy*100))

Accuracy: %f 93.75
